Fixed the script. It now uses some apikeys I found from https://ocdnix.wordpress.com/2013/02/28/pulling-warranty-details-from-api-dell-com/

diff --git a/dellWarrantyCheck b/dellWarrantyCheck
--- a/dellWarrantyCheck
+++ b/dellWarrantyCheck
@@ -1,11 +1,44 @@
 #!/bin/bash
 
-# Author: Sabuj Pattanayek (sabuj.pattanayek@vanderbilt.edu)
-# Purpose: Gets remaining warranty information from dell.com for the system that this script is run on.
+# Author: Sabuj Pattanayek (sabujp@gmail.com)
+# Purpose: Gets remaining warranty information from dell.com for the system
+# that this is run on. Run as root, with sudo, or dmidecode must be setuid root.
+# Also needs wget or curl, tr, sed, grep, and awk. Only works with Linux due to
+# it crawling /proc for other info.
+# Flags: --csv : output in csv mode
+#        --noheader : don't output the header line for the csv
 # Version: git
 
-# run as root, with sudo, or /usr/sbin/dmidecode must be setuid root
+find_command() {
+	locations=( /usr/sbin /usr/bin /bin /sbin /usr/local/bin /usr/local/sbin )
+	for dir in ${locations[@]}; do
+		if [[ -e ${dir}/${1} ]]; then
+			command="${dir}/$1"
+			echo $command
+		fi
+	done
+	if [[ "$2" == "required" ]]; then
+		echo "Can not find $1"
+		exit 1
+	fi
+	echo 0
+}
 
+days_remaining() {
+	endDate=$(date -d "$1" +%s)
+  currentDate=$(date +%s)
+	echo $(( (endDate - currentDate) / (60*60*24) ))
+}
+
+# Look for needed commands
+dmidecode=$(find_command dmidecode required)
+get_http="$(find_command wget optional)"
+if [[ $get_http == 0 ]]; then
+	get_http="$(find_command curl required) -s -k"
+else
+	get_http="$get_http -q --no-check-certificate -O -"
+fi
+lspci=$(find_command lspci required)
 
 for var in "$@"
 do
@@ -17,20 +50,29 @@ do
 	fi
 done
 
-if [[ -e "/usr/sbin/dmidecode" && $USER == "root" ]]; then
-	dmidecode="/usr/sbin/dmidecode"
-else
-	dmidecode="/sb/apps/Linux/bin/dmidecode"
+serial=`$dmidecode -s chassis-serial-number`
+if [[ $? != 0 ]]; then
+	echo "Could not get the serial number, quitting"
+	exit 1
 fi
-serial=`$dmidecode | grep -i "Serial Number" | head -1 | awk -F' ' '{print $3}' | sed 's/[ \t]\+/ /g'`
-model=`$dmidecode | grep "Product Name" | head -1 | sed -e 's/Product Name: //' | sed 's/[ \t]\+/ /g' | sed 's/^[ \t]//'`
-mem=`cat /proc/meminfo | grep -i memtotal | sed 's/[ \t]\+/ /g' | sed 's/MemTotal: //'` 
-cpuType=`cat /proc/cpuinfo | grep -i "model name" | head -1 | sed 's/[ \t]\+/ /g' | sed 's/model name : //'`
-cpuNum=`cat /proc/cpuinfo | grep -i processor | wc -l | head -1 | sed 's/[ \t]\+/ /g'`
-cpuMHz=`cat /proc/cpuinfo | grep -i "cpu mhz" | head -1 | awk -F' ' '{print $4}' | sed 's/[ \t]\+/ /g'`
+model=`$dmidecode -s system-product-name`
+mem=`cat /proc/meminfo | grep -i memtotal | sed 's/[ \t]\+/ /g' | sed \
+	's/MemTotal: //'` 
+cpuType=`cat /proc/cpuinfo | grep -i "model name" | head -1 | sed \
+	's/[ \t]\+/ /g' | sed 's/model name : //'`
+cpuNum=`cat /proc/cpuinfo | grep -i processor | wc -l | head -1 | sed \
+	's/[ \t]\+/ /g'`
+cpuMHz=`cat /proc/cpuinfo | grep -i "cpu mhz" | head -1 | awk -F' ' \
+	'{print $4}' | sed 's/[ \t]\+/ /g'`
 uptime=`uptime | sed 's/[ \t]\+/ /g' | sed 's/^[ \t]//'`;
-lastPerson=`last | grep " :0" | head -1 | sed 's/[ \t]\+/ /g'`
-gpus=`cat /proc/driver/nvidia/gpus/*/information | grep Model | sed -e 's/Model: //' | sed 's/[ \t]\+/ /g' | sed 's/^[ \t]//' | tr '\n' ','`
+lastPerson=`last | grep " :0" | head -1 | sed 's/[ \t]\+/ /g' | \
+	awk '{print $1}'`
+gpus=`cat /proc/driver/nvidia/gpus/*/information | grep Model | sed -e \
+	's/Model: //' | sed 's/[ \t]\+/ /g' | sed 's/^[ \t]//' | tr '\n' ','`
+if [[ $gpus == "" ]]; then
+	gpus=`lspci | grep -i "vga compatible" | sed 's/[ \t]\+/ /g' | sed \
+		's/^[ \t]//' | tr '\n' ','`
+fi
 hostName=`hostname`
 
 print () {
@@ -45,71 +87,42 @@ print () {
 		echo "GPUS: ${gpus}"
 		echo "LAST CONSOLE USER: ${lastPerson}"
 		echo "UPTIME: ${uptime}"
-		# line commented below only works with dmidecode from RHEL5 boxes
-		#serial=`/sb/apps/Linux/bin/dmidecode -s system-serial-number`
-		#daysLeft=`wget -q "http://support.euro.dell.com/support/topics/topic.aspx/emea/shared/support/my_systems_info/en/details?ServiceTag=${serial}" -O - | grep contract_table | awk -F'<td' '{print $12}' | awk -F'>' '{print $2}' | awk -F'<' '{print $1}'`
-		#echo "WARRANTY REMAINING: $daysLeft"
-		echo "WARRANTY END DATE: $endDate"
+		echo "WARRANTY DAYS REMAINING: ${daysLeft}"
 	else
 		if [[ ! $noHeader ]]; then
-			#echo "HOSTNAME;MODEL;SERIAL;MEMORY;CPU TYPE;CPU MHZ (possibly throttled);NUM LOGICAL CPUS;GPUS;LAST CONSOLE USER;UPTIME;WARRANTY DAYS REMAINING"
-			echo "HOSTNAME;MODEL;SERIAL;MEMORY;CPU TYPE;CPU MHZ (possibly throttled);NUM LOGICAL CPUS;GPUS;LAST CONSOLE USER;UPTIME;WARRANTY END DATE"
+			echo "HOSTNAME;MODEL;SERIAL;MEMORY;CPU TYPE;CPU MHZ \
+(possibly throttled);NUM LOGICAL CPUS;GPUS;LAST CONSOLE USER;UPTIME;\
+WARRANTY DAYS REMAINING"
 		fi
-		#echo "${hostName};${model};${serial};${mem};${cpuType};${cpuMHz};${cpuNum};${gpus};${lastPerson};${uptime};${daysLeft}"
-		echo "${hostName};${model};${serial};${mem};${cpuType};${cpuMHz};${cpuNum};${gpus};${lastPerson};${uptime};${endDate}"
+		echo "${hostName};${model};${serial};${mem};${cpuType};${cpuMHz};${cpuNum};${gpus};${lastPerson};${uptime};${daysLeft}"
 	fi
 }
 
-# method 7
-endDate=`wget -q "http://www.dell.com/support/my-support/us/en/555/product-support/servicetag/${serial}?s=BSD" -O - | grep -i "Warranty end date" | awk -F">" '{print $2}' | awk '{print $1}' | awk -F"<" '{print $1}' | head -1`
-if [[ -n $endDate ]]; then
-	print
-	exit
-fi
+apikeys=( "d676cf6e1e0ceb8fd14e8cb69acd812d" \
+	"849e027f476027a394edd656eaef4842" )
+for key in ${apikeys[@]}; do
+	endDate=`$get_http "https://api.dell.com/support/v2/assetinfo/warranty/\
+tags.xml?svctags=${serial}&apikey=${key}" | grep -i enddate | \
+		awk -F'>' '{print $2}' | awk -F'T' '{print $1}' | tr '\n' ' ' | xargs`
+	endDates=( $endDate )
+	if [[ ${#endDates[@]} > 0 ]]; then
+		break
+	fi
+done
 
-# method 6
-endDate=`wget -q http://www.dell.com/support/troubleshooting/us/en/555/Servicetag/${serial}#ui-tabs-5 -O - | grep "Warranty with an end date of" | awk -F"<b>" '{print $3}' | awk -F"</b>" '{print $1}'`
-if [[ -n $endDate ]]; then
-	print
-	exit
-fi
-
-# method 5
-daysLeft=`wget -q "http://www.dell.com/support/troubleshooting/us/en/04/Index?t=warranty&servicetag=${serial}" -O - | grep TopTwoWarrantyListItem | head -1 | awk -F'<b>' '{print $2}' | awk -F'[' '{print $2}' | awk -F']' '{print $1}'`
-if [[ -n $daysLeft ]]; then
-	print
-	exit
-fi
-
-
-# method 4
-daysLeft=`wget -q "http://support.dell.com/support/topics/global.aspx/support/my_systems_info/details?c=us&l=en&s=gen&ServiceTag=${serial}" -O - | grep TopTwoWarrantyListItem | head -1 | awk -F'<b>' '{print $2}' | awk -F'[' '{print $2}' | awk -F']' '{print $1}'`
-if [[ -n $daysLeft ]]; then
-	print
-	exit
-fi
-
-# method 1
-daysLeft=`wget -q "http://support.dell.com/support/topics/global.aspx/support/my_systems_info/details?c=us&l=en&s=gen&ServiceTag=${serial}" -O - | grep contract_oddrow | awk -F'<td' '{print $12}' | awk -F'>' '{print $3}' | awk -F'<' '{print $1}'`
-if [[ -n $daysLeft ]]; then
-	print
-	exit
-fi
-
-# method 2
-daysLeft=`wget -q "http://support.dell.com/support/topics/global.aspx/support/my_systems_info/details?c=us&l=en&s=gen&ServiceTag=${serial}" -O - | grep contract_oddrow | awk -F'<td' '{print $12}' | awk -F'>' '{print $2}' | awk -F'<' '{print $1}'`
-if [[ -n $daysLeft ]]; then
-	print
-	exit
-fi
-
-# method 3
-daysLeft=`wget -q "http://support.dell.com/support/topics/global.aspx/support/my_systems_info/details?c=us&l=en&s=gen&ServiceTag=${serial}" -O - | grep contract_oddrow | awk -F'<td' '{print $12}' | awk -F'>' '{print $4}' | awk -F'<' '{print $1}'`
-if [[ -n $daysLeft ]]; then
-	print
-	exit
+if [[ ${#endDates[@]} == 0 ]]; then
+	daysLeft='?'
 else
-	print
-	echo "WARRANTY REMAINING: ERROR! Exhausted all search patterns please contact Sabuj Pattanayek (sabuj.pattanayek@vanderbilt.edu) if you're running this on a Dell system that has a correct serial number to have this script fixed"
+	# Absolute maximum negative days remaining on a warranty would be from when
+	# Dell started as a company sometime in 1984
+	daysLeft=$(days_remaining "Jan 1 1984")
+	for endDate in ${endDates[@]}; do
+		tmpDaysLeft=$(days_remaining $endDate)
+		if (( $tmpDaysLeft > $daysLeft )); then
+			daysLeft=$tmpDaysLeft
+		fi
+	done
 fi
+
+print
 
